name: 'Kubernetes set context'
description: 'Kubernetes set context'
inputs: 
# Used for setting the target K8s cluster context which will be used by other actions like azure/k8s-actions/k8s-deploy or azure/k8s-actions/k8s-create-secret
  kubeconfig:
    description: 'Kubernetes Config'
    required: false
    default: ''
    deprecationMessage: "This action is ARCHIVED and will not receive any updates, update your workflows to use the new action azure/k8s-set-context@v1"
  context:
    description: 'If your kubeconfig has multiple contexts, use this field to use a specific context, otherwise the default one would be chosen'
    required: false
    default: ''

  k8s-url:
    description: 'Cluster Url'
    required: false
    default: ''
  k8s-secret:
    description: 'Service account token'
    required: false
    default: ''
  
branding:
  color: 'green' # optional, decorates the entry in the GitHub Marketplace
runs:
  using: 'node12'
  main: 'lib/login.js'
